# Sidebar navigation

- label: เกี่ยวกับเรา
  link: /
- label: Net MD
  items:
    - label: คู่มือติดตั้งโปรแกรม SonicStage 4.3 สำหรับ Windows 10 64-bit
      link: /net-md/sonic-stage-installation-manual
    - label: คู่มือใช้งาน Web MiniDisc
      link: /net-md/web-mini-disc-manual
    - label: รู้จัก MD recording mode
      link: /net-md/md-recording-mode

    - label: ทดสอบเวลาที่ในการเขียนเพลง MP3 ลงแผ่น MD
      link: /net-md/writing-disc-time-usage-test
    - label: ชื่อรุ่นของ Sony MD players
      link: /net-md/md-player-model-number
    - label: รีโมทรุ่นต่างๆ ของ Sony MD
      link: /net-md/sony-md-remotes

    - label: MD lens cleaner
      link: /net-md/md-lens-cleaner
